Blog App -validations and model specs.
Amen-Musingarimi/blog-app pull request #3
Opened 2023-06-08 22:30 UTC by Amen-Musingarimi

## What I did:
- [ ] Add the following validations:
- For the User model:
`Name must not be blank`.
`PostsCounter must be an integer greater than or equal to zero.`
- For the Post model:
`Title must not be blank.`
`Title must not exceed 250 characters.`
`CommentsCounter must be an integer greater than or equal to zero.`
`LikesCounter must be an integer greater than or equal to zero.`
- [ ] Add unit specs for all of your models' methods and validations.

2023-06-08 22:57 UTC, jerryowusu requested changes
Hi @Amen-Musingarimi 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

![almost got it](https://github.com/Amen-Musingarimi/blog-app/assets/65233860/fb54cad0-2d1c-4dc8-a611-e5d53239647d)


## Highlights
:heavy_check_mark: User model has validations
:heavy_check_mark: Post model has validations


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 22:57 UTC, jerryowusu commented on spec/models/comment_spec.rb
> +end
Nice job so far. However, as part of the project requirements, any custom methods in the models should have a corresponding unit test. In view of this kindly add unit test for the `update_post_comment_counter` method in the comment model here. :wink:

2023-06-08 22:57 UTC, jerryowusu commented on spec/models/like_spec.rb
> +end
Nice job so far. However, as part of the project requirements, any custom methods in the models should have a corresponding unit test. In view of this kindly add unit test for the `update_post_like_counter` method in the like model here. :wink:

2023-06-08 22:57 UTC, jerryowusu commented on spec/models/user_spec.rb
> +end
Nice job so far. However, as part of the project requirements, any custom methods in the models should have a corresponding unit test. In view of this kindly add unit test for the `recent_posts` method in the user model here. :wink:

2023-06-08 22:57 UTC, jerryowusu commented on spec/models/post_spec.rb
> +end
Nice job so far. However, as part of the project requirements, any custom methods in the models should have a corresponding unit test. In view of this kindly add unit test for the `update_user_post_counter` and `five_most_recent_comments` methods in the post model here. :wink:

2023-06-09 10:10 UTC, elisha2kyakpo1 requested changes
Hi 👋 @Amen-Musingarimi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

👍 You did well in adding tests for the model methods as requested by the previous reviewer.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 10:10 UTC, elisha2kyakpo1 commented on spec/models/user_spec.rb
> +    end
- [ ] Kindly add more post examples for you to be sure the recent_posts method works, currently, it's difficult to know because you only have 3 posts and it's obvious that the available posts will be returned.
__HINT:__
 ```Ruby
  describe '#recent_posts' do
    before do
      6.times do |p|
        Post.create(title: "Post #{p}", text: "Text #{p}", comments_counter: 10, author_id: subject.id,
                    likes_counter: 10)
      end
    end

    it 'returns the three most recent posts' do
      expect(subject.recent_posts).to eq(subject.posts.order(created_at: :desc).limit(3))
    end
  end
 ```

2023-06-09 10:10 UTC, elisha2kyakpo1 commented on spec/models/comment_spec.rb
> +  end
- [ ] I suggest you test for a situation where a comment(s) is added as well, we would like to see the counter update.

2023-06-09 10:10 UTC, elisha2kyakpo1 commented on spec/models/like_spec.rb
>    end
- [ ] As requested by the previous reviewer, kindly add a test for the likes_counter, put in mind the scenario where a like is not yet added, and after adding a like.

2023-06-09 10:10 UTC, elisha2kyakpo1 commented on spec/models/post_spec.rb
> +    end
- [ ] I suggest you test for a situation where a post(s) is added as well, we would like to see the counter update.

2023-06-09 12:55 UTC, BregornOriginal approved these changes
Hi @Amen-Musingarimi 

Your project is complete!  There is nothing else to say other than... it's time to merge it 

Congratulations! 

## Highlights

✅ Linters are passing
✅ Excellent commit history
✅ Good PR title and description
✅ Rspec is passing 💯 

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2023-06-12 14:17 UTC, merged